# render.yaml
services:
  - type: web
    name: vertexsol-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: vertexsol-db
          property: connectionString
